# Generated by Django 5.0.3 on 2024-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='/user-avatars/no-avatar.jpg', null=True, upload_to='user-avatars/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Windows', 'Windows'), ('Linux', 'Linux'), ('MacOS', 'MacOS'), ('Off-topic', 'Off-topic')], default='', max_length=255),
        ),
    ]
